import type { Table } from "./types";

export const TABLES: Table[] = [
  {
    id: "1",
    name: "Стіл 1",
    number: 1,
    position: { x: 0, y: 0 },
    seats: 2,
    shape: "round",
    status: "available",
  },
  {
    id: "2",
    name: "Стіл 2",
    number: 2,
    position: { x: 1, y: 0 },
    seats: 2,
    shape: "round",
    status: "occupied",
  },
  {
    id: "3",
    name: "Стіл 3",
    number: 3,
    position: { x: 2, y: 0 },
    seats: 4,
    shape: "square",
    status: "reserved",
  },
  {
    id: "4",
    name: "Стіл 4",
    number: 4,
    position: { x: 0, y: 1 },
    seats: 4,
    shape: "square",
    status: "available",
  },
  {
    id: "5",
    name: "Стіл 5",
    number: 5,
    position: { x: 1, y: 1 },
    seats: 6,
    shape: "rectangle",
    status: "occupied",
  },
  {
    id: "6",
    name: "Стіл 6",
    number: 6,
    position: { x: 2, y: 1 },
    seats: 6,
    shape: "rectangle",
    status: "available",
  },
  {
    id: "7",
    name: "Стіл 7",
    number: 7,
    position: { x: 0, y: 2 },
    seats: 8,
    shape: "rectangle",
    status: "maintenance",
  },
  {
    id: "8",
    name: "Стіл 8",
    number: 8,
    position: { x: 1, y: 2 },
    seats: 4,
    shape: "square",
    status: "available",
  },
  {
    id: "9",
    name: "Стіл 9",
    number: 9,
    position: { x: 2, y: 2 },
    seats: 2,
    shape: "round",
    status: "reserved",
  },
  {
    id: "10",
    name: "Барна стійка",
    number: 10,
    position: { x: 0, y: 3 },
    seats: 10,
    shape: "rectangle",
    status: "occupied",
  },
  {
    id: "11",
    name: "VIP-кімната",
    number: 11,
    position: { x: 1, y: 3 },
    seats: 12,
    shape: "rectangle",
    status: "available",
  },
  {
    id: "12",
    name: "Стіл 12",
    number: 12,
    position: { x: 2, y: 3 },
    seats: 4,
    shape: "square",
    status: "reserved",
  },
];
