import type { Customer } from "./types";

export const CUSTOMERS: Customer[] = [
  {
    email: "alex@example.com",
    id: "1",
    lastVisit: "28.02.2026",
    name: "Олександр Шевченко",
    notes: "Предпочитає столи біля вікна",
    phone: "+380 67 123 4567",
    tags: ["Поціновувач стейків", "Бізнес-ланчі"],
    totalSpent: 15400,
    vip: true,
    visits: 12,
  },
  {
    email: "maria@example.com",
    id: "2",
    lastVisit: "25.02.2026",
    name: "Марія Коваленко",
    notes: "",
    phone: "+380 50 987 6543",
    tags: ["Вегетаріанець"],
    totalSpent: 8200,
    vip: false,
    visits: 8,
  },
  {
    email: "ivan@example.com",
    id: "3",
    lastVisit: "28.02.2026",
    name: "Іван Бондаренко",
    notes: "Часто замовляє для компаній",
    phone: "+380 93 111 2233",
    tags: ["Постійний клієнт", "Дні народження"],
    totalSpent: 32800,
    vip: true,
    visits: 24,
  },
  {
    email: "anna@example.com",
    id: "4",
    lastVisit: "15.01.2026",
    name: "Анна Петренко",
    notes: "",
    phone: "+380 63 444 5566",
    tags: [],
    totalSpent: 2100,
    vip: false,
    visits: 3,
  },
  {
    email: "dmytro@example.com",
    id: "5",
    lastVisit: "27.02.2026",
    name: "Дмитро Сидоренко",
    notes: "Приходить з родиною по вихідних",
    phone: "+380 95 777 8899",
    tags: ["Сімейні обіди"],
    totalSpent: 18900,
    vip: true,
    visits: 15,
  },
  {
    email: "natalia@example.com",
    id: "6",
    lastVisit: "20.02.2026",
    name: "Наталія Козак",
    notes: "Любить лаунж-зону",
    phone: "+380 98 222 3344",
    tags: ["Кава", "Десерти"],
    totalSpent: 5400,
    vip: false,
    visits: 6,
  },
];
